"""Add freebies table and relationships

Revision ID: 0dc899ced09d
Revises: 90b7caa391fa
Create Date: 2025-05-26 11:48:37.615119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc899ced09d'
down_revision = '90b7caa391fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
